
name: Update Submodule

on:
  push:
    branches:
      - 16.0

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodule
        run: |
          git submodule init
          git submodule update --remote
          git add .
          git commit -m "Update submodule to reflect main repository changes"
          git push
