name: Update Test Repository

on:
  push:
    branches:
      - '16.0'

jobs:
  update-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodule
        run: |
          git submodule update --remote --merge
          cd Test
          git add .
          git commit -m "Update submodule from common Muram"
          git push origin main
