name: Update Test Submodule

on:
  push:
    branches:
      - '16.0'  # Replace with the branch name that triggers the update

jobs:
  update_test_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: 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
          repository: muram-105/Test
          event-type: update-test-submodule
