name: Update Test Submodule

on:
  push:
    branches:
      - '16.0'  # Replace with the branch name that triggers the update

jobs:
  update_test_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Test submodule
        run: |
          # Determine the path of the Test submodule in the Test repository
          TEST_SUBMODULE_PATH=$(find . -type d -name "Common" | head -n 1)

          # Change to the Test submodule directory
          cd $GITHUB_WORKSPACE/$TEST_SUBMODULE_PATH

          # Update the submodule
          git checkout '16.0'
          git pull

          # Commit and push the submodule update
          git add .
          git commit -m "Update Test submodule" --no-verify
          git push origin '16.0'
