name: Push to Test Submodule

on:
  push:
    branches:
      - '16.0'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push changes to Test repository
        run: |
          git config --global user.name "muram-105"
          git config --global user.email "muram8700@gmail.com"
          cd path/to/common/submodule # Replace with the actual path to your common submodule
          git remote set-url origin https://github.com/muram-105/Test.git # Replace with the URL of your test repository
          git push origin HEAD:main
