name: Update Test Submodule

on:
  push:
    branches:
      - '16.0'

jobs:
  update_test_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: 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
          repository: muram-105/Common
          event-type: update-test-submodule
