name: Sync Submodule

on:
  push:
    branches:
      - '16.0'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Submodule
        run: |
          git config --global user.name "muram-105"
          git config --global user.email "muram8700@gmail.com"
          git submodule sync
          git submodule update --remote --merge
          git commit -am "Sync Submodule" || echo "No changes to submodule"
          git push
