name: Sync Submodules

on:
  push:
    branches:
      - 16.0

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config user.email "muram8700@gmail.com"
          git config user.name "muram105"

      - name: Sync submodules
        run: |
          git submodule sync
          git submodule update --init --recursive
          git submodule foreach 'git checkout main && git pull origin main'

      - name: Log completion
        run: echo "Submodule synchronization completed"
