name: Update Submodules

on:
  push:
    branches:
      - 16.0

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Submodules
        run: |
          git submodule sync
          git submodule update --init --recursive
          git submodule foreach 'git checkout 16.0 && git pull origin 16.0'
          git commit -am "Updated submodules"
          git push origin 16.0
