name: Sync Submodule common in test

on:
  push:
    branches:
      - '16.0'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Submodule
        env:
          COMMON_ACCESS_TOKEN: ${{ secrets.TEST_REPO_TOKEN }}
        run: |
          git config --global user.name "muram-105"
          git config --global user.email "muram8700@gmail.com"
          git submodule sync
          git submodule update --remote --merge --init --recursive
          cd common
          git config credential.helper "store --file=.git/credentials"  # Store credentials temporarily
          git config user.name "muram-105"
          git config user.email "muram8700@gmail.com"
          git fetch --all
          git checkout 16.0
          git pull origin 16.0 --rebase
          cd ..
          git add common
          git commit -m "Sync Submodule" || echo "No changes to submodule"
          git push --set-upstream origin 16.0
