name: Update Submodules

on:
  push:
    branches:
      - '16.0'

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Common repository
        uses: actions/checkout@v2

      - name: Update Submodules
        run: |
          # Define the list of repositories and their respective submodules
          repos:
            - name: Test
              submodule: common

          git config user.name "muram-105"
          git config user.email "muram8700@gmail.com"
          
          # Get the path of the Test repository
          test_repo_path=${{ github.workspace }}/Test
          
          # Loop through the repositories and update submodules
          for repo in "${repos[@]}"; do
            submodule="${repo[submodule]}"
            
            cd "$test_repo_path"
            git submodule update --remote "$submodule"
            cd ..
          done
          
          # Commit and push changes
          git add .
          git commit -m "Update submodules"
          git push origin HEAD:${{ github.ref }}
