name: Dispatch Workflow

on:
  push:
    branches:
      - '16.0'

jobs:
  dispatch_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Dispatch Workflow in Another Repository
        run: |
          # Set your access token and the target repository name
          ACCESS_TOKEN="${{ secrets.TEST_TOKEN }}"
          TARGET_REPO="muram-105/Test"
          
          # Set the event type you want to trigger
          EVENT_TYPE="update-test-submodule"
          
          # Dispatch the repository event using the GitHub API
          curl -X POST \
            -H "Authorization: token $ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/$TARGET_REPO/dispatches" \
            -d "{\"event_type\": \"$EVENT_TYPE\"}"
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.TEST_TOKEN }}
