name: Update Test Submodule

on:
  push:
    branches:
      - '16.0'

jobs:
  update_test_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: muram-105/Test
          event-type: update-test-submodule
          client-payload: |
            {
              "submodule": "Common",
              "message": "Dispatch event from repo-b to repo-a",
              "commit": "${{ github.sha }}"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
