name: Print Token

on:
  push:
    branches:
      - '16.0'

jobs:
  print_token:
    runs-on: ubuntu-latest

    steps:
      - name: Print Token
        run: echo "${{ secrets.COMMON_REPO_TOKEN }}"
