name: Sync Repositories
on:
  push:
    branches:
      - '16.0' # Adjust this based on your main branch name

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo-A
        uses: actions/checkout@v2

      - name: Sync Changes to Repo-B
        run: |
          git config --global user.email "muram8700@gmail.com"
          git config --global user.name "muram-105"
          git remote add repo-b https://github.com/muram-105/Test.git
          git push Test HEAD:main
        env:
          REPO_B_PAT: ${{ secrets.TEST_TOKEN }}
