name: Update Test Submodule

on:
  push:
    branches:
      - '16.0'

jobs:
  update_test_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_TOKEN }} # Replace with your personal access token
          repository: muram-105/Test
          event-type: update-test-submodule
          client-payload: |
            {
              "submodule": "Common",
              "message": "Dispatch event from repo-b to repo-a",
              "commit": "${{ github.sha }}"
            }
