name: Sync Submodule (Common)

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "muram-105"
          git config --global user.email "your.email@example.com"

      - name: Update submodule
        run: |
          git submodule sync
          git submodule update --recursive --remote

      - name: Commit and push changes
        run: |
          git commit -am "Sync submodule"
          git remote set-url origin https://$TEST_REPO_TOKEN@github.com/muram-105/Common.git
          git push
