name: Update Test Submodule

on:
  push:
    branches:
      - '16.0'

jobs:
  update_test_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TEST_TOKEN }}
          repository: muram-105/Test
          event-type: update-test-submodule
          client-payload: |
            {
              "submodule": "Common",
              "message": "Dispatch event from repo-b to repo-a",
              "commit": "${{ github.sha }}"
            }
